name 'artisol-nslcd'
version '0.0.1'

author 'Johan Lyheden'
license ''
project_page 'https://bitbucket.org/jlyheden/puppet-nslcd'
source 'git@bitbucket.org:jlyheden/puppet-nslcd.git'
summary 'Manages the nslcd daemon'
description ''
dependency 'puppetlabs/stdlib', '==3.2.0'
