name 'jlyheden-nslcd'
version '0.0.1'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://github.com/jlyheden/puppet-nslcd'
source 'git@github.com:jlyheden/puppet-nslcd.git'
summary 'Manages the nslcd daemon'
description 'A Puppet module to manage the nslcd daemon which provides authentication via LDAP'
dependency 'puppetlabs/stdlib', '>=3.2.0'
